name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '21.5'

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build

    - name: Package into zip
      run: zip -r package.zip dist manifest.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: package.zip
      id: upload-artifact

    - name: Get Artifact URL
      run: "echo \"Artifact URL: ${{ steps.upload-artifact.outputs.artifact_url }}\""